DemoMvc4/Controllers/HomeController.cs
using System.Web.Mvc;

namespace DemoMvc4
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Examples()
        {
            return View();
        }
    }
}

DemoMvc4/Controllers/PayrollController.cs
using DemoMvc4.Models;
using iTextSharp.text;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace DemoMvc4.Controllers
{
    public class PayrollController : Controller
    {
        //
        // GET: /Payroll/

        public ActionResult Index()
        {
            var examples = ExampleSpec.ExamplesStatic();
            return View(examples);
        }

        public ActionResult Example(uint id)
        {
            var examples = ExampleSpec.ExamplesStatic();
            ExampleSpec exampleSpec = examples.Single((x) => (x.Id == id));

            var example = new PayrollExample(exampleSpec);

            return View(example);
        }

        public FileStreamResult DownloadPDF(uint id)
        {
            var examples = ExampleSpec.ExamplesStatic();
            ExampleSpec exampleSpec = examples.Single((x) => (x.Id == id));

            var example = new PayrollExample(exampleSpec);

            var stream = new MemoryStream();

            example.CreatePDF(stream, false);

            return File(stream, "text/pdf", "Paycheck.pdf");
        }

        public FileStreamResult DownloadXML(uint id)
        {
            var examples = ExampleSpec.ExamplesStatic();
            ExampleSpec exampleSpec = examples.Single((x) => (x.Id == id));

            var example = new PayrollExample(exampleSpec);

            string stringXML = example.CreateXML();

            var byteArray = Encoding.ASCII.GetBytes(stringXML);

            var stream = new MemoryStream(byteArray);

            return File(stream, "text/xml", "Paycheck.xml");
        }
    }
}

DemoMvc4/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Mzdy Hravě";
}

<div class="page-header">
    <h1>@ViewBag.Title <small>by Mzdy Hravě&reg;</small></h1>
    <p>We are here to make a payroll agenda now, simple and clear for everyone.</p>
</div>

<div id="payroll-carousel" class="carousel slide">
    <div class="carousel-inner">
        <div class="active item">
            <img src="~/Content/images/CarouselSlide/Carousel7-Payroll.jpg" alt="">
            <div class="container">
                <div class="carousel-caption">
                    <p class="lead">Simple Payroll? Payroll as a game for small business.</p>
                    <br />
                    <a class="btn btn-large btn-primary" href="@Url.Action("Index", "Payroll")">Try examples</a>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="~/Content/images/CarouselSlide/Carousel7-Click.jpg" alt="">
            <div class="container">
                <div class="carousel-caption">
                    <p class="lead">Just a few clicks to get payroll from timesheet to direct deposit.
                    </p>
                    <br />
                    <a class="btn btn-large btn-primary" href="@Url.Action("Index", "Payroll")">Try examples</a>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="~/Content/images/CarouselSlide/Carousel7-Paycheck.jpg" alt="">
            <div class="container">
                <div class="carousel-caption">
                    <p class="lead">All done simple from timesheet to paycheck. No paperwork definitely.
                    </p>
                    <br />
                    <a class="btn btn-large btn-primary" href="@Url.Action("Index", "Payroll")">Try examples</a>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="~/Content/images/CarouselSlide/Carousel7-Easy.jpg" alt="">
            <div class="container">
                <div class="carousel-caption">
                    <p class="lead">Completely and accurately. With save about $200 a month.</p>
                    <br />
                    <a class="btn btn-large btn-primary" href="@Url.Action("Index", "Payroll")">Try examples</a>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="~/Content/images/CarouselSlide/Carousel7-Love.jpg" alt="">
            <div class="container">
                <div class="carousel-caption">
                    <p class="lead">You and your staff will love it. To learn, teach, create, inspire.
                    </p>
                    <br />
                    <a class="btn btn-large btn-primary" href="@Url.Action("Index", "Payroll")">Try examples</a>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="~/Content/images/CarouselSlide/Carousel7-Payroll2.jpg" alt="">
            <div class="container">
                <div class="carousel-caption">
                    <p class="lead">Simple Payroll? Payroll as a game for small business.</p>
                    <br />
                    <a class="btn btn-large btn-primary" href="@Url.Action("Index", "Payroll")">Try examples</a>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="~/Content/images/CarouselSlide/Carousel7-Click2.jpg" alt="">
            <div class="container">
                <div class="carousel-caption">
                    <p class="lead">Just a few clicks to get payroll from timesheet to direct deposit.
                    </p>
                    <br />
                    <a class="btn btn-large btn-primary" href="@Url.Action("Index", "Payroll")">Try examples</a>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="~/Content/images/CarouselSlide/Carousel7-Paycheck2.jpg" alt="">
            <div class="container">
                <div class="carousel-caption">
                    <p class="lead">All done simple from timesheet to paycheck. No paperwork definitely.
                    </p>
                    <br />
                    <a class="btn btn-large btn-primary" href="@Url.Action("Index", "Payroll")">Try examples</a>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="~/Content/images/CarouselSlide/Carousel7-Easy2.jpg" alt="">
            <div class="container">
                <div class="carousel-caption">
                    <p class="lead">Completely and accurately. With save about $200 a month.</p>
                    <br />
                    <a class="btn btn-large btn-primary" href="@Url.Action("Index", "Payroll")">Try examples</a>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="~/Content/images/CarouselSlide/Carousel7-Love2.jpg" alt="">
            <div class="container">
                <div class="carousel-caption">
                    <p class="lead">You and your staff will love it. To learn, teach, create, inspire.
                    </p>
                    <br />
                    <a class="btn btn-large btn-primary" href="@Url.Action("Index", "Payroll")">Try examples</a>
                </div>
            </div>
        </div>
    </div>
    <a class="carousel-control left" href="#payroll-carousel" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#payroll-carousel" data-slide="next">&rsaquo;</a>
</div>

<script>
    !function ($) {
        $(function () {
            // carousel demo
            $('#payroll-carousel').carousel()
        })
    }(window.jQuery)
</script>